### ISSUE TITLE
Ability to send sockets to child process/spawned process handle

### ISSUE THREAD

**Issue by Rush** [VanCoding/node-ancillary#2]
As TCP/HTTP server for sharing sockets is a bit overblown for my usage (and I worry about security precautions) I would request a following feature:

In server:

```
var ancillary = require('ancillary');
var thisFunctionAcceptsServerConnection = function(socket) {
    var child = fork('child.js');
    ancillary.sendHandleToChildProcess(child, 'optionalMessage', 
}
```

child.js

```
var ancillary = require('ancillary');
ancillary.onParentHandle(function(handle, msg) {

});
```

You already have code to serialize/deserialize handles, it only needs to utilize process.on(...) and processHandle.send(...). What do you think? Real advantage is that it would utilize existing communication channels that node.js creates for each child process.

**Comment by VanCoding** [comment]
See my answer on your following topic:
https://github.com/VanCoding/node-ancillary/issues/1#issuecomment-6079614
