### ISSUE TITLE
EACESS while trying to listen

### ISSUE THREAD

**Issue by Rush** [VanCoding/node-ancillary#3]
Problem is best illustrated on your own example:

```
/node-ancillary/examples> node simple_parent.js

events.js:48
        throw arguments[1]; // Unhandled 'error' event
                       ^
Error: listen EACCES
    at errnoException (net.js:670:11)
    at Array.0 (net.js:756:28)
    at EventEmitter._tickCallback (node.js:190:38)
```

Here is my strace: http://dragon.rushbase.net/~rush/ancillary.out

If there are any additional steps to make this work please give any hints. I was trying to run the program both from root and from normal user.
System is openSUSE 12.1 with fairly standard config.

**Comment by VanCoding** [comment]
Could you maybe tell me wich node version you are using?

**Comment by Rush** [comment]
Node version 0.6.18

This fixed the problem:

```
touch node_modules/node-ancillary/sockets/
```

Actually the strace said it all, it was just a bit confusing that the location is there.. So your lib seems to be working fine. Not only for example but for my own usage as well.
