### ISSUE TITLE
cannot be executed successfully in v0.7.7 and v0.8

### ISSUE THREAD

**Issue by cmkpl** [VanCoding/node-ancillary#4]
When I compile and run the addon on v0.7.7 (linux) and v0.8 (mac), it cannot be executed successfully.

v0.8:

> var ancillary = require("./ancillary");
> ancillary

{}

v0.7.7:

> var ancillary = require('./build/Release/ancillary');
> ancillary

{ GetFD: [Function],
  Send: [Function],
  Receive: [Function] }

it does not contain the function such as createHttpServer

**Comment by VanCoding** [comment]
Node.js 0.8 uses the new build system "gyp", so I guess node-ancillary won't be able to build for it.
On 0.7.7 it seems to work for you! You just require the wrong thing ;) just require the index.js file.

I'm currently working on a new version of ancillary which is cross platform and uses another technique to transfer handles to other processes. The API of node-ancillary will stay the same, so don't worry to work with the current build.

To continue my work on the new version, I first need to get an answer to the following feature request:
https://github.com/joyent/node/issues/3551

If they don't implement it, i'll have to do it by my own wich will take me more time.

**Comment by cmkpl** [comment]
yeah! thanks, I included the wrong thing, by var ancillary = require("./index.js");, it works!
