### ISSUE TITLE
After sending the socket handle to another process, the listener of the original process is gone?

### ISSUE THREAD

**Issue by cmkpl** [VanCoding/node-ancillary#5]
the original process (A):

```
var ancillary = require('./VanCoding-node-ancillary-b396659/index.js');
var net = require('net');


var server = net.createServer(function (socket) {
    ancillary.send("myuniqueID",socket);
    socket.on("data", function(data){
        socket.write("A\n");
    });
});

server.listen(8000, function() {

});
```

Another process (B) listening for the socket handle:

```
var ancillary = require('./VanCoding-node-ancillary-b396659/index.js');
var net = require('net');

ancillary.createServer(function(socket){
    socket.on("data", function(data){
        console.log(socket);
        socket.write("B\n");
    });
}).listen("myuniqueID");
```

After passing the socket handle to B, it seems that process A does not know data is coming, but I need it. Even I rebind the event, it does not help:

```
ancillary.send("myuniqueID", socket);

setTimeout(function(){
    socket.on("data", function(data){
        socket.write("lalala\n");
    });
}, 1000);
```

 Is there any way to solve? Thanks.

**Comment by VanCoding** [comment]
Sadly, it's not possible to make multiple processes getting the same data from the same socket. When one process reads data from the socket, its gone for all other processes.

Of course you can just resume the socket after sending it using `socket.resume()` and make it reading data again. But this results only in a competition of the processes for the data. You will not know which process will get it.

So, you ever have to decide which process needs the data. If process A need the date, resume the socket on process A and pause the socket on process B (and vice versa).

If you want process A AND B to get the data, you'll have to take another approach. You could for example open a connection to process B and pipe the data to it.

Hope this helps..

**Comment by cmkpl** [comment]
oh, yes. `socket.resume()` seems like what I need. In fact, I would like the original process to continue to listen. For the new one, it only used to send.

I am testing its stability.

**Comment by cmkpl** [comment]
oops. It seems like there is resource competition.

I need to keep issuing `socket.resume()` after receiving each time. But still, it cannot ensure data can be received.

**Comment by cmkpl** [comment]
To handle the problem, I have made the following changes in lib/ancillary.js

comment these lines:
https://github.com/VanCoding/node-ancillary/blob/b396659398bb6dc32dfab766b7ab64621e923f38/lib/ancillary.js#L32
https://github.com/VanCoding/node-ancillary/blob/b396659398bb6dc32dfab766b7ab64621e923f38/lib/ancillary.js#L96

change socket.writable = false on this line:
https://github.com/VanCoding/node-ancillary/blob/b396659398bb6dc32dfab766b7ab64621e923f38/lib/ancillary.js#L30

But it only applies to my case:
1. the original process is still the only listener
2. another process is used to send data

Also, I am still testing.
