### ISSUE TITLE
Sending socket limited to ~130 simultaneously 

### ISSUE THREAD

**Issue by cmkpl** [VanCoding/node-ancillary#6]
Maybe this is not the designed use case for node-ancillary. But if I tried to do something like:

```
for (var i = 0; i < 1000; i++){
    // the function signature is changed for testing the case
    ancillary.send("myuniqueID", socket, i);
}
```

Another process

```
ancillary.createServer(function(socket, data){
    console.log(data);
    try{
        socket.write(data + "\n");
        socket.destroy();
        socket.end();
    } catch(e){
        //...
    }

}).listen("myuniqueID");
```

Server side can only receive ~130 of the requests. This is my ulimit -a data:

```
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 13133
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 200000
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 13133
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```

Even I create 100 ancillary servers in the same process, and distribute the data to 100 servers, it seems it can work. All data can be sent. It shows that it is not process limit but socket limit. but I don't want to spawn 100 servers for accepting data simultaneously.

Any idea? Thanks!

**Comment by VanCoding** [comment]
Have you tried to delay your socket sendings a bit?
The problem is, that the current code is blocking for a short time to receive a socket. I'm working on a completely unblocking version, but I have some problems with libuv.

I hope this problem will be gone after the switch to libuv...

**Comment by cmkpl** [comment]
Yup, delaying the socket ending will help the situation. Hope you can solve the problems with libuv as high data usage is used for my service. Thanks!

**Comment by cmkpl** [comment]
Also, there is memory leak for sending by ancillary. I haven't checked the source of the leak. Just to tell you first.

**Comment by VanCoding** [comment]
Ok, I've made the switch from the (blocking) ancillary library to node.js' pipes. For me it works really well.
Did this change fix the limitations you metioned above?
